### ISSUE TITLE
A couple of bugs/features

### ISSUE THREAD

**Issue by wibron** [slowmove/Spotify-Embed-Creator#6]
Hi! 

I've listed some things that might improve this plugin: 
- The ability to search by a URI of a track, album or artist. Is it possible? 
- If you check the 'compact'-checkbox after you've submited a search, the textarea with the embed/shortcode should be updated and match the settings.
- If I click on an artist or album in the list generated by the response (admin-view), I'll navigate to # (use preventDefault on that anchor)
- I can't seem to get any preview of how the embed will look while editing a post. It's possible when I navigate to the item in the menubar. 

Cheers!

**Comment by slowmove** [comment]
Added them as separate issues.
